CREATE TABLE t_p99057007_project_continuation.characters (
    id SERIAL PRIMARY KEY,
    user_id INTEGER UNIQUE REFERENCES t_p99057007_project_continuation.users(id),
    name VARCHAR(32) NOT NULL,
    class VARCHAR(32) DEFAULT 'hacker',
    level INTEGER DEFAULT 1,
    xp INTEGER DEFAULT 0,
    xp_to_next INTEGER DEFAULT 500,
    hp INTEGER DEFAULT 100,
    max_hp INTEGER DEFAULT 100,
    coins INTEGER DEFAULT 50,
    stat_strength INTEGER DEFAULT 10,
    stat_agility INTEGER DEFAULT 10,
    stat_intelligence INTEGER DEFAULT 10,
    stat_defense INTEGER DEFAULT 10,
    stat_luck INTEGER DEFAULT 10,
    equip_head INTEGER REFERENCES t_p99057007_project_continuation.items(id),
    equip_body INTEGER REFERENCES t_p99057007_project_continuation.items(id),
    equip_weapon INTEGER REFERENCES t_p99057007_project_continuation.items(id),
    equip_gloves INTEGER REFERENCES t_p99057007_project_continuation.items(id),
    equip_boots INTEGER REFERENCES t_p99057007_project_continuation.items(id),
    equip_implant INTEGER REFERENCES t_p99057007_project_continuation.items(id),
    current_chapter INTEGER DEFAULT 1,
    current_quest VARCHAR(64) DEFAULT 'intro',
    created_at TIMESTAMP DEFAULT NOW()
)
